name: eutel_mobile_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.9
  go_router: ^13.1.0
  responsive_sizer: ^3.3.0+1
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  intl: ^0.19.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  country_pickers: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash_image/
    - assets/images/on_boarding_image/
    - assets/images/login_images/
    - assets/images/

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packagessss

  fonts:
    - family: DMSans-VariableFont_opsz,wght
      fonts:
        - asset: assets/googleFont/DM_Sans/DMSans-VariableFont_opsz,wght.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: DMSans-Italic-VariableFont_opsz,wght
      fonts:
        - asset: assets/googleFont/DM_Sans/DMSans-Italic-VariableFont_opsz,wght.ttf

    - family: Urbanist
      fonts:
        - asset: assets/googleFont/Urbanist-Italic-VariableFont_wght.ttf
        - asset: assets/googleFont/Urbanist-VariableFont_wght.ttf
          weight: 700
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
